version: "3.4"
services:
  web:
    ports:
      - ${HOST_PORT}:${PORT}
    build: .
    tty: true

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 3.10.0.0/16
          gateway: 3.10.0.1
