version: "3.4"
services:
  web:
    ports:
      - 8080:8080
    build: .
    tty: true

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 3.10.0.0/16
          gateway: 3.10.0.1
